###########################################
# BASE IMAGE
###########################################
FROM ubuntu:latest

RUN apt-get -q update ; apt-get -yq install python3 python3-pip

EXPOSE 8080

ADD . /
